import 'package:flutter/material.dart';

extension ExpansionTileExtension on ExpansionTile {
  ExpansionTile copyWith({
    Key? key,
    Widget? leading,
    Widget? title,
    Widget? subtitle,
    ValueChanged<bool>? onExpansionChanged,
    List<Widget>? children,
    Widget? trailing,
    bool? initiallyExpanded,
    bool? maintainState,
    EdgeInsetsGeometry? tilePadding,
    Alignment? expandedAlignment,
    CrossAxisAlignment? expandedCrossAxisAlignment,
    EdgeInsetsGeometry? childrenPadding,
    Color? backgroundColor,
    Color? collapsedBackgroundColor,
    Color? textColor,
    Color? collapsedTextColor,
    Color? iconColor,
    Color? collapsedIconColor,
    ShapeBorder? shape,
    ShapeBorder? collapsedShape,
    Clip? clipBehavior,
    ListTileControlAffinity? controlAffinity,
    ExpansionTileController? controller,
    bool? dense,
    VisualDensity? visualDensity,
    bool? enableFeedback,
    bool? enabled,
    AnimationStyle? expansionAnimationStyle,
  }) {
    return ExpansionTile(
      key: key ?? this.key,
      leading: leading ?? this.leading,
      title: title ?? this.title,
      subtitle: subtitle ?? this.subtitle,
      onExpansionChanged: onExpansionChanged ?? this.onExpansionChanged,
      trailing: trailing ?? this.trailing,
      initiallyExpanded: initiallyExpanded ?? this.initiallyExpanded,
      maintainState: maintainState ?? this.maintainState,
      tilePadding: tilePadding ?? this.tilePadding,
      expandedAlignment: expandedAlignment ?? this.expandedAlignment,
      expandedCrossAxisAlignment:
          expandedCrossAxisAlignment ?? this.expandedCrossAxisAlignment,
      childrenPadding: childrenPadding ?? this.childrenPadding,
      backgroundColor: backgroundColor ?? this.backgroundColor,
      collapsedBackgroundColor:
          collapsedBackgroundColor ?? this.collapsedBackgroundColor,
      textColor: textColor ?? this.textColor,
      collapsedTextColor: collapsedTextColor ?? this.collapsedTextColor,
      iconColor: iconColor ?? this.iconColor,
      collapsedIconColor: collapsedIconColor ?? this.collapsedIconColor,
      shape: shape ?? this.shape,
      collapsedShape: collapsedShape ?? this.collapsedShape,
      clipBehavior: clipBehavior ?? this.clipBehavior,
      controlAffinity: controlAffinity ?? this.controlAffinity,
      controller: controller ?? this.controller,
      dense: dense ?? this.dense,
      visualDensity: visualDensity ?? this.visualDensity,
      enableFeedback: enableFeedback ?? this.enableFeedback,
      enabled: enabled ?? this.enabled,
      expansionAnimationStyle:
          expansionAnimationStyle ?? this.expansionAnimationStyle,
      children: children ?? this.children,
    );
  }
}
