name: Publish Package

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      latest:
        description: 'Latest: release the latest image'
        type: boolean
        default: true
      version:
        description: 'Version: image version/tag to release'
        type: string
        required: false

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          version: latest

      - name: Install dependencies
        run: flutter pub get

      - name: Check code formatting
        run: |
          dart format --set-exit-if-changed .
          echo "✓ Code formatting is correct"

      - name: Run analyzer
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Verify pubspec
        run: |
          flutter pub upgrade --major-versions
          flutter test
          flutter pub publish --dry-run

      - name: Publish to pub.dev
        if: success()
        run: flutter test
        #flutter pub publish --force
        env:
          PUB_CREDENTIALS: ${{ secrets.PUB_DEV_PUBLISH_TOKEN }}